language: generic

services:
  - docker

after_succes:
  - docker build -t chaoslecion123/djangofer -f  compose/production/django/Dockerfile . 

  - echo "$DOCKER_PASSWORD" | docker login -u "chaoslecion123" -p "Newyesterday123."  docker.io

  - docker images

  - docker push chaoslecion123/djangofer

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multicontainer-docker-tutorial-fernando
  env: Multicontainerdockertutorialfernando-env
  access_key_id: $AWS_ACCESS_KEY 
  secret_access_key: $AWS_SECRET_KEY
  bucket_name: "buckets-travis-2022fer"
  bucket_path: "docker"
  on:
    branch: dev