# Generated by Django 2.0.9 on 2022-09-29 21:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_auto_20191205_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 21, 1, 35, 539978, tzinfo=utc)),
        ),
    ]
