# Generated by Django 2.0.9 on 2022-09-29 21:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_auto_20220929_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 21, 58, 18, 702323, tzinfo=utc)),
        ),
    ]
