# Generated by Django 2.0.9 on 2022-09-29 22:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0005_auto_20220929_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 22, 12, 0, 75066, tzinfo=utc)),
        ),
    ]
