# Generated by Django 2.0.9 on 2022-09-29 22:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_auto_20220929_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 29, 22, 21, 44, 294199, tzinfo=utc)),
        ),
    ]
